name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - 'v*'

  # Allows the workflow to be ran by another one
  workflow_call:

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: LaTeX compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: cv.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: cv
          path: cv.pdf

      - name: Release PDF
        uses: softprops/action-gh-release@v0.1.13
        with:
          files: |
            cv.pdf
