name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '*'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: LaTeX compilation (english)
        uses: dante-ev/latex-action@2023-A
        with:
          root_file: cv-english.tex
          extra_system_packages: ghostscript
          entrypoint: ./release.sh

      - name: LaTeX compilation (french)
        uses: dante-ev/latex-action@2023-A
        with:
          root_file: cv-french.tex
          extra_system_packages: ghostscript
          entrypoint: ./release.sh
      
      - name: LaTeX compilation (german)
        uses: dante-ev/latex-action@2023-A
        with:
          root_file: cv-german.tex
          extra_system_packages: ghostscript
          entrypoint: ./release.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: cv
          path: |
            cv-english.pdf
            cv-english.png
            cv-french.pdf
            cv-french.png
            cv-german.pdf
            cv-german.png

      - name: Release PDF and PNG files
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            cv-english.pdf
            cv-english.png
            cv-french.pdf
            cv-french.png
            cv-german.pdf
            cv-german.png
